name: Trigger auto deployment for contosoair-v3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/contosoair-v3-AutoDeployTrigger-1c0518d0-a39f-4519-8baf-cc64f0e6b663.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cad7c8812b26acr.azurecr.io
          username: ${{ secrets.CONTOSOAIRV3_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTOSOAIRV3_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cad7c8812b26acr.azurecr.io/contosoair-v3:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTOSOAIRV3_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n contosoair-v3 -g xp-containersdemo-rg --server cad7c8812b26acr.azurecr.io --username  ${{ secrets.CONTOSOAIRV3_REGISTRY_USERNAME }} --password ${{ secrets.CONTOSOAIRV3_REGISTRY_PASSWORD }}
            az containerapp update -n contosoair-v3 -g xp-containersdemo-rg --image cad7c8812b26acr.azurecr.io/contosoair-v3:${{ github.sha }}
